M48
; DRILL file {KiCad (6.0.4-0)} date Monday, February 13, 2023 at 03:54:30 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-13T15:54:30-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1772
%
G90
G05
T1
X2.6555Y-1.6457
X2.6555Y-4.8957
X6.1555Y-4.8957
T0
M30
